# Docker Compose file Reference (https://docs.docker.com/compose/compose-file/)

version: '3.7'

# Define services
services:
  # App backend service
  tilgung-microservice:
    # Configuration for building the docker image for the backend service
    build:
      context: tilgung-microservice # Use an image built from the specified dockerfile in the tilgung-microservice.
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # Forward the exposed port 8080 on the container to port 8080 on the host machine
    restart: always
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - backend
      - frontend

  # Frontend Service
  react-frontend:
    build:
      context: react-frontend # Use an image built from the specified dockerfile in the `polling-app-client` directory.
      dockerfile: Dockerfile
    ports:
      - "3000:80" # Forward the exposed port 80 on the container to port 3000 on the host machine
    restart: always
    depends_on:
      - tilgung-microservice
    networks:
      - frontend

# Volumes
volumes:
  db-data:

# Networks to be created to facilitate communication between containers
networks:
  backend:
  frontend:
